##
# Cloudflare Wrangler configuration.
#
# @since 1.0.0
#
# @see https://github.com/toml-lang/toml
# @see https://developers.cloudflare.com/workers/cli-wrangler/configuration/
##
compatibility_date = "2022-04-16"
type = "javascript"

name = "skeleton-cfw"
kv_namespaces = []

account_id = "f1176464a976947aa5665d989814a4b1"
zone_id = ""
route = ""

[env.staging]
workers_dev = true

[build]
command = "composer compile"

[build.upload]
format = "service-worker"

[dev]
port = 8787
ip = "127.0.0.1"
local_protocol = "http"
upstream_protocol = "https"
